# 📊 Data Preprocessing

The primary objective of this notebook is to **preprocess** the raw Eur/Usd data. This step is essential to ensure the dataset is structured performing Exploratory Data Analysis (EDA) and Feature Engineering.

## 1. Data Acquisition

We acquire historical hourly data for Eur/Usd from 2011 to the present. To achieve this, we utilize the custom script `src/eurusd_data_extraction.py`, which joins multiple datasets of **Histdata**.

In [2]:
import pandas as pd

# We load the datasets
df_5mins = pd.read_pickle('../data/EURUSD_5M.pkl')
df_1h = pd.read_pickle('../data/EURUSD_1H.pkl')
df_1d = pd.read_pickle('../data/EURUSD_1D.pkl')

# We take a look at the data
df_1h

                        open     high      low    close  volume
timestamp
2011-01-02 17:00:00  1.33450  1.33620  1.33410  1.33420       0
2011-01-02 18:00:00  1.33430  1.33610  1.33330  1.33550       0
2011-01-02 19:00:00  1.33560  1.33580  1.33160  1.33210       0
2011-01-02 20:00:00  1.33200  1.33230  1.32750  1.32810       0
2011-01-02 21:00:00  1.32820  1.32980  1.32760  1.32810       0
...                      ...      ...      ...      ...     ...
2025-12-05 12:00:00  1.16340  1.16441  1.16324  1.16441       0
2025-12-05 13:00:00  1.16441  1.16485  1.16420  1.16425       0
2025-12-05 14:00:00  1.16426  1.16440  1.16399  1.16430       0
2025-12-05 15:00:00  1.16429  1.16445  1.16397  1.16440       0
2025-12-05 16:00:00  1.16439  1.16471  1.16400  1.16428       0

[91572 rows x 5 columns]

As we can see above, there are 69103 rows, which makes a big amount of data. 

## 2. Data Loading & Inspection

We inspect dataset's structure and data types.

In [6]:
# Data info
df_1h.info()
# Statistical summary
df_1h[['open', 'high', 'low', 'close', 'volume']].describe()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 91572 entries, 2011-01-02 17:00:00 to 2025-12-05 16:00:00
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   open    91572 non-null  float64
 1   high    91572 non-null  float64
 2   low     91572 non-null  float64
 3   close   91572 non-null  float64
 4   volume  91572 non-null  int64
dtypes: float64(4), int64(1)
memory usage: 4.2 MB

               open          high           low         close   volume
count  91572.000000  91572.000000  91572.000000  91572.000000  91572.0
mean       1.177698      1.178522      1.176896      1.177698      0.0
std        0.109115      0.109208      0.109020      0.109114      0.0
min        0.953900      0.955920      0.953570      0.953900      0.0
25%        1.094560      1.095300      1.093810      1.094558      0.0
50%        1.139855      1.140725      1.139100      1.139860      0.0
75%        1.250513      1.251412      1.249645      1.250498      0.0
max        1.493300      1.493900      1.490400      1.493200      0.0

There are no null values, so there is no matter to worry about them.

## 3. Dealing with volume

As for every row the volume is zero, we are deleting the column.

In [7]:
df_5mins.drop(columns=['volume'], inplace=True)
df_1h.drop(columns=['volume'], inplace=True)
df_1d.drop(columns=['volume'], inplace=True)    

df_1h

                        open     high      low    close
timestamp
2011-01-02 17:00:00  1.33450  1.33620  1.33410  1.33420
2011-01-02 18:00:00  1.33430  1.33610  1.33330  1.33550
2011-01-02 19:00:00  1.33560  1.33580  1.33160  1.33210
2011-01-02 20:00:00  1.33200  1.33230  1.32750  1.32810
2011-01-02 21:00:00  1.32820  1.32980  1.32760  1.32810
...                      ...      ...      ...      ...
2025-12-05 12:00:00  1.16340  1.16441  1.16324  1.16441
2025-12-05 13:00:00  1.16441  1.16485  1.16420  1.16425
2025-12-05 14:00:00  1.16426  1.16440  1.16399  1.16430
2025-12-05 15:00:00  1.16429  1.16445  1.16397  1.16440
2025-12-05 16:00:00  1.16439  1.16471  1.16400  1.16428

[91572 rows x 4 columns]

## 4. Saving the Processed Dataset

Finally, we save the cleaned and preprocessed DataFrame to a new CSV file.

In [8]:
df_5mins.to_pickle('../data/EURUSD_5M_preprocessed.pkl')
df_1h.to_pickle('../data/EURUSD_1H_preprocessed.pkl')
df_1d.to_pickle('../data/EURUSD_1D_preprocessed.pkl')